version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always 
    container_name: my-mysql_01
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test_database
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/my.cnf

